#!/usr/bin/env python3
import os
import re
import sys

# Leanguages igit
igit_cpp = '''# Prerequisites
*.d

# Compiled Object files
*.slo
*.lo
*.o
*.obj

# Precompiled Headers
*.gch
*.pch

# Linker files
*.ilk

# Debugger Files
*.pdb

# Compiled Dynamic libraries
*.so
*.dylib
*.dll

# Fortran module files
*.mod
*.smod

# Compiled Static libraries
*.lai
*.la
*.a
*.lib

# Executables
*.exe
*.out
*.app

# debug information files
*.dwo'''

igit_c = '''# Prerequisites
*.d

# Object files
*.o
*.ko
*.obj
*.elf

# Linker output
*.ilk
*.map
*.exp

# Precompiled Headers
*.gch
*.pch

# Libraries
*.lib
*.a
*.la
*.lo

# Shared objects (inc. Windows DLLs)
*.dll
*.so
*.so.*
*.dylib

# Executables
*.exe
*.out
*.app
*.i*86
*.x86_64
*.hex

# Debug files
*.dSYM/
*.su
*.idb
*.pdb

# Kernel Module Compile Results
*.mod*
*.cmd
.tmp_versions/
modules.order
Module.symvers
Mkfile.old
dkms.conf

# debug information files
*.dwo'''

igit_go = '''# If you prefer the allow list template instead of the deny list, see community template:
# https://github.com/github/gitignore/blob/main/community/Golang/Go.AllowList.gitignore
#
# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with `go test -c`
*.test

# Code coverage profiles and other test artifacts
*.out
coverage.*
*.coverprofile
profile.cov

# Dependency directories (remove the comment below to include it)
# vendor/

# Go workspace file
go.work
go.work.sum

# env file
.env

# Editor/IDE
# .idea/
# .vscode/'''

igit_gradle = '''.gradle
**/build/
!**/src/**/build/

# Ignore Gradle GUI config
gradle-app.setting

# Avoid ignoring Gradle wrapper jar file (.jar files are usually ignored)
!gradle-wrapper.jar

# Avoid ignore Gradle wrappper properties
!gradle-wrapper.properties

# Cache of project
.gradletasknamecache

# Eclipse Gradle plugin generated files
# Eclipse Core
.project
# JDT-specific (Eclipse Java Development Tools)
.classpath'''

igit_java = '''# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
hs_err_pid*
replay_pid*'''

igit_langchain = '''# gitignore template for LangChain products, e.g., LangGraph, LangSmith
# website: https://www.langchain.com/
# website: https://www.langchain.com/langgraph

# LangGraph
.langgraph_api/'''

igit_maven = '''target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties
# https://maven.apache.org/wrapper/#usage-without-binary-jar
.mvn/wrapper/maven-wrapper.jar

# Eclipse m2e generated files
# Eclipse Core
.project
# JDT-specific (Eclipse Java Development Tools)
.classpath'''

igit_node = '''# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.*
!.env.example

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist
.output

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# vuepress v2.x temp and cache directory
.temp
.cache

# Sveltekit cache directory
.svelte-kit/

# vitepress build output
**/.vitepress/dist

# vitepress cache directory
**/.vitepress/cache

# Docusaurus cache and generated files
.docusaurus

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# Firebase cache directory
.firebase/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v3
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions

# Vite files
vite.config.js.timestamp-*
vite.config.ts.timestamp-*
.vite/'''

igit_python = '''# Byte-compiled / optimized / DLL files
__pycache__/
*.py[codz]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py.cover
.hypothesis/
.pytest_cache/
cover/

# Translations
*.mo
*.pot

# Django stuff:
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal

# Flask stuff:
instance/
.webassets-cache

# Scrapy stuff:
.scrapy

# Sphinx documentation
docs/_build/

# PyBuilder
.pybuilder/
target/

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# pyenv
# .python-version

# pipenv
# Pipfile.lock

# UV
# uv.lock

# poetry
# poetry.lock
# poetry.toml

# pdm
# pdm.lock
# pdm.toml
.pdm-python
.pdm-build/

# pixi
# pixi.lock
.pixi

# PEP 582
__pypackages__/

# Celery stuff
celerybeat-schedule
celerybeat.pid

# Redis
*.rdb
*.aof
*.pid

# RabbitMQ
mnesia/
rabbitmq/
rabbitmq-data/

# ActiveMQ
activemq-data/

# SageMath parsed files
*.sage.py

# Environments
.env
.envrc
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject

# Rope project settings
.ropeproject

# mkdocs documentation
/site

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Pyre
.pyre/

# pytype
.pytype/

# Cython debug symbols
cython_debug/

# PyCharm
# .idea/

# Abstra
.abstra/

# Visual Studio Code
# .vscode/

# Ruff stuff
.ruff_cache/

# PyPI configuration
.pypirc

# Marimo
marimo/_static/
marimo/_lsp/
__marimo__/

# Streamlit
.streamlit/secrets.toml'''

igit_qt = '''# C++ objects and libs
*.slo
*.lo
*.o
*.a
*.la
*.lai
*.so
*.so.*
*.dll
*.dylib

# Qt-es
object_script.*.Release
object_script.*.Debug
*_plugin_import.cpp
/.qmake.cache
/.qmake.stash
*.pro.user
*.pro.user.*
*.qbs.user
*.qbs.user.*
*.moc
moc_*.cpp
moc_*.h
qrc_*.cpp
ui_*.h
*.qmlc
*.jsc
Makefile*
*build-*
*.qm
*.prl

# Qt unit tests
target_wrapper.*

# QtCreator
*.autosave

# QtCreator Qml
*.qmlproject.user
*.qmlproject.user.*

# QtCreator CMake
CMakeLists.txt.user*

# QtCreator 4.8< compilation database
compile_commands.json

# QtCreator local machine specific files for imported projects
*creator.user*

*_qmlcache.qrc'''

igit_scala = '''*.class
*.log

# virtual machine crash logs
hs_err_pid*'''

igit_swift = '''# Xcode

## User settings
xcuserdata/

## Obj-C/Swift specific
*.hmap

## App packaging
*.ipa
*.dSYM.zip
*.dSYM

## Playgrounds
timeline.xctimeline
playground.xcworkspace

# Swift Package Manager
.build/

# CocoaPods
# Pods/

# Carthage
Carthage/Build/

# fastlane
fastlane/report.xml
fastlane/Preview.html
fastlane/screenshots/**/*.png
fastlane/test_output'''

igit_tex = '''## Core latex/pdflatex auxiliary files:
*.aux
*.lof
*.log
*.lot
*.fls
*.out
*.toc
*.fmt
*.fot
*.cb
*.cb2
.*.lb

## Intermediate documents:
*.dvi
*.xdv
*-converted-to.*
# *.ps
# *.eps
# *.pdf

## Generated if empty string is given at "Please type another file name for output:"
.pdf

## Bibliography auxiliary files
*.bbl
*.bbl-SAVE-ERROR
*.bcf
*.bcf-SAVE-ERROR
*.blg
*-blx.aux
*-blx.bib
*.run.xml

## Build tool auxiliary files
*.fdb_latexmk
*.synctex
*.synctex(busy)
*.synctex.gz
*.synctex.gz(busy)
*.pdfsync
*.rubbercache
rubber.cache

## Build tool directories
latex.out/

## Auxiliary/intermediate from other packages
*.alg
*.loa
*.thm
*.cut
*.cpt
*.spl
*.ent
*.lox
*.mf
*.mp
*.t[1-9]
*.tfm
*.end
*.[1-9]
*.acn
*.acr
*.glg
*.glo
*.gls
*.lol
*.idx
*.ilg
*.ind
*.maf
*.mlf
*.mlt
*.mtc[0-9]*
*.pyg
*.mw
*.nlg
*.nlo
*.nls
*.pax
*.pdfpc
*.sagetex.sage
*.sagetex.py
*.sagetex.scmd
*.wrt
*.spell.bad
*.spell.txt
*.upa
*.upb
*.pytxcode
pythontex-files-*/
*.listing
*.loe
*.dpth
*.md5
*.auxlock
*.ptc
*.tdo
*.hst
*.ver
*.lod
*.xcp
*.xmpi
*.xdy
*.xyc
*.xyd
*.ttt
*.fff
TSWLatexianTemp*
*.bak
*.sav
*.bak[0-9]*
.texpadtmp
*.lyx~
*.backup
.*.swp
*~[0-9]*
*.tps
./auto/*
*.el
*-tags.tex
*.sta
*.lpz
*.xwm
#*Notes.bib'''

igit_terraform = '''# Local .terraform directories
.terraform/

# .tfstate files
*.tfstate
*.tfstate.*

# Crash log files
crash.log
crash.*.log

# Sensitive data files
*.tfvars
*.tfvars.json

# Ignore override files
override.tf
override.tf.json
*_override.tf
*_override.tf.json

# Lock info files
.terraform.tfstate.lock.info

# CLI config files
.terraformrc
terraform.rc'''

# OS igit
igit_linux = '''*~

.fuse_hidden*
.directory
.Trash-*
.nfs*
nohup.out'''

igit_windows = '''# Windows thumbnail cache files
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db

# Dump file
*.stackdump

# Folder config file
[Dd]esktop.ini

# Recycle Bin
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

# Windows shortcuts
*.lnk'''

igit_macos = '''# General
.DS_Store
__MACOSX/
.AppleDouble
.LSOverride
Icon[
]

# Thumbnails
._*

# Files in root of volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Remote AFP
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk'''

# Editors igit
igit_vsc = '''.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets
!*.code-workspace

# Built VS Code Extensions
*.vsix'''

igit_xcode = '''## User settings
xcuserdata/'''

igit_jetbrains = '''
# Covers JetBrains IDEs
# Reference: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

# User-specific stuff
.idea/**/workspace.xml
.idea/**/tasks.xml
.idea/**/usage.statistics.xml
.idea/**/dictionaries
.idea/**/shelf

# AWS
.idea/**/aws.xml

# Generated
.idea/**/contentModel.xml

# Sensitive/high-churn
.idea/**/dataSources/
.idea/**/dataSources.ids
.idea/**/dataSources.local.xml
.idea/**/sqlDataSources.xml
.idea/**/dynamic.xml
.idea/**/uiDesigner.xml
.idea/**/dbnavigator.xml

# Gradle
.idea/**/gradle.xml
.idea/**/libraries

# CMake
cmake-build-*/

# Mongo Explorer
.idea/**/mongoSettings.xml

# File-based project format
*.iws

# IntelliJ
out/

# sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Cursive plugin
.idea/replstate.xml

# SonarLint plugin
.idea/sonarlint/
.idea/sonarlint.xml

# Crashlytics plugin
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties

# Editor-based HTTP Client
.idea/httpRequests
http-client.private.env.json

# Android Studio cache file
.idea/caches/build_file_checksums.ser

# Apifox
.idea/.cache/.Apifox_Helper
.idea/ApifoxUploaderProjectSetting.xml
'''

# Dictionaries: option to gitignore section
languages_to_igit_dict = {
    "cpp": igit_cpp,
    "c": igit_c,
    "go": igit_go,
    "gradle": igit_gradle,
    "java": igit_java,
    "langchain": igit_langchain,
    "maven": igit_maven,
    "node": igit_node,
    "python": igit_python,
    "qt": igit_qt,
    "scala": igit_scala,
    "swift": igit_swift,
    "tex": igit_tex,
    "terraform": igit_terraform,
}

system_to_igit_dict = {
    "linux": igit_linux,
    "windows": igit_windows,
    "macos": igit_macos,
}

editors_to_igit_dict = {
    "vsc": igit_vsc,
    "xcode": igit_xcode,
    "jetbrains": igit_jetbrains,
}

def check_if_section_exist(section_name:str, file_name:str = ".gitignore") -> bool:
    with open(file_name, 'r') as file:
        line = file.readline()
        while line:
            if line.startswith(f"# ======= {section_name} ======="):
                return True
            line = file.readline()
    return False

def add_section(section_name:str) -> None:
    if check_if_section_exist(section_name, ".gitignoret"):
        print(f"[ERROR] Section {section_name} already exists")
        sys.exit(1)

    section_content = ""
    section_type = ""

    if section_name in languages_to_igit_dict:
        section_type = "Languages"
        section_content = languages_to_igit_dict[section_name]

    if section_name in editors_to_igit_dict:
        section_type = "Editors"
        section_content = editors_to_igit_dict[section_name]

    if section_name in system_to_igit_dict:
        section_type = "System"
        section_content = system_to_igit_dict[section_name]

    os.rename(".gitignoret", ".gitignorebuff")

    with open(".gitignoret", "x") as gitignore, open(".gitignorebuff", 'r') as gitignorebuff:
        line = gitignorebuff.readline()

        while line:
            if line.startswith(f"# =-=-=-=-=-=-=-=-=-= END {section_type} =-=-=-=-=-=-=-=-=-="):
                gitignore.write(f"# ======= {section_name} =======\n")
                gitignore.write(section_content + '\n')
                gitignore.write(f"# ======= END {section_name} =======\n\n")
            gitignore.write(line)
            line = gitignorebuff.readline()

    os.remove(".gitignorebuff")

def remove_section(section_name:str) -> None:
    if not check_if_section_exist(section_name, ".gitignoret"):
        print(f"[ERROR] Section {section_name} already does not exist")
        sys.exit(1)

    os.rename(".gitignoret", ".gitignorebuff")

    with open(".gitignoret", "x") as gitignore, open(".gitignorebuff", 'r') as gitignorebuff:
        line = gitignorebuff.readline()
        section_flag = False

        while line:
            if line.startswith(f"# ======= {section_name} ======="):
                section_flag = True
            elif line.startswith(f"# ======= END {section_name} ======="):
                section_flag = False
                gitignorebuff.readline()
                line = gitignorebuff.readline()

            if not section_flag:
                gitignore.write(line)

            line = gitignorebuff.readline()

    os.remove(".gitignorebuff")

# def print_the_state() -> None:
#     print("Currently in .gitignore")
#
#     print("Languages:")
#     for name,state in languages_state.items():
#         print(f"\t-{name}: {1 if state else 0}")
#
#     print("System:")
#     for name,state in system_state.items():
#         print(f"\t-{name}: {1 if state else 0}")
#
#     print("Editors:")
#     for name,state in editors_state.items():
#         print(f"\t-{name}: {1 if state else 0}")

if __name__ == "__main__":
    it = iter(sys.argv[1:])

    # Option excluding states
    creating_igit_state = False
    modifying_igit_state = False

    # Option such as: --exc triggers the state, then in option_selected, the option that was recently choosen is being holds
    option_state = False
    option_selected = ""

    for arg in it:
        # parsing the arguments
        if arg.startswith("--"):
            option_state = True
            option_selected = arg.strip('-')
            continue

        if modifying_igit_state and creating_igit_state:
            print("[ERROR] You cannot modify and create gitignore at the same time")

        # adding option
        if option_state and re.match('add_*', option_selected):
            modifying_igit_state = True

            if not(option_selected == "add_lang" or option_selected == "add_editor" or option_selected == "add_system"):
                print(f"[ERROR] Invalid option given. No such option as {option_selected}")
            else:
                cutted_option = re.sub('add_', '', option_selected)
                match cutted_option:
                    case 'lang':
                        if arg not in languages_to_igit_dict:
                            print(f"[ERROR] Invalid parameter given. No such language gitingore section as {arg}")
                        else:
                            add_section(arg)
                    case 'sys':
                        if arg not in system_to_igit_dict:
                            print(f"[ERROR] Invalid parameter given. No such system gitingore section as {arg}")
                        else:
                            add_section(arg)
                    case 'editor':
                        if arg not in editors_to_igit_dict:
                            print(f"[ERROR] Invalid parameter given. No such editor gitingore section as {arg}")
                        else:
                            add_section(arg)
                    case _:
                        print(f'[ERROR] Bad option given. No such option as {option_selected}')




    if len(sys.argv) == 1:
        with open(".gitignoret", "w") as file:
            file.write("# =-=-=-=-=-=-=-=-=-= Languages =-=-=-=-=-=-=-=-=-=\n\n")
            file.write("# =-=-=-=-=-=-=-=-=-= END Languages =-=-=-=-=-=-=-=-=-=\n\n\n\n")
            file.write("# =-=-=-=-=-=-=-=-=-= System =-=-=-=-=-=-=-=-=-=\n\n")
            file.write("# =-=-=-=-=-=-=-=-=-= END System =-=-=-=-=-=-=-=-=-=\n\n\n\n")
            file.write("# =-=-=-=-=-=-=-=-=-= Editors =-=-=-=-=-=-=-=-=-=\n\n")
            file.write("# =-=-=-=-=-=-=-=-=-= END Editors =-=-=-=-=-=-=-=-=-=\n\n\n\n")
            file.write("# =-=-=-=-=-=-=-=-=-= Custom User Section =-=-=-=-=-=-=-=-=-=\n\n")
            file.write("# =-=-=-=-=-=-=-=-=-= END Custom User Section =-=-=-=-=-=-=-=-=-=")
            file.flush()
        #
        # for lang_name in languages_to_igit_dict.keys():
        #     add_section(lang_name)
        #
        # for system_name in system_to_igit_dict.keys():
        #     add_section(system_name)
        #
        # for editor_name in editors_to_igit_dict.keys():
        #     add_section(editor_name)
        #
        # remove_section("java")